name: Test Environment Secrets

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Select the environment"
        required: true
        default: "staging"
        type: choice
        options:
          - sfl
          - lms

jobs:
  print-secrets:
    runs-on: ubuntu-latest

    steps:

      - name: Print Secrets for Selected Environment
        run: |
          echo "Host: ${{ secrets[format('EC2_HOST_{0}', github.event.inputs.environment)] }}"
          echo "Username: ${{ secrets[format('EC2_USERNAME_{0}', github.event.inputs.environment)] }}"
