name: Transfer Files to EC2

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Select the environment"
        required: true
        default: "sfl"
        type: choice
        options:
          - sfl
          - lms

jobs:
  transfer:
    runs-on: ubuntu-latest

    steps:
      - name: Transfer files to EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets[format('EC2_HOST_${{ github.event.inputs.environment | upper }}')] }}
          username: ${{ secrets[format('EC2_USERNAME_${{ github.event.inputs.environment | upper }}')] }}
          key: ${{ secrets[format('SSH_PRIVATE_KEY_${{ github.event.inputs.environment | upper }}')] }}
          source: 'super_admin_data.json'
          target: '/var/www/html/'
