name: Fetch Hostname and Username

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Select the environment"
        required: true
        default: "sfl"
        type: choice
        options:
          - sfl
          - lms

jobs:
  fetch-environment-vars:
    runs-on: ubuntu-latest

    steps:
      - name: Display Selected Environment
        run: echo "Selected environment:"${{ github.event.inputs.environment }}
      - name: Print Repository Environment Variables
        env:
          ENV_VAR_1: ${{ vars.ENV_VAR_1 }}
        run: echo "ENV_VAR_1: $ENV_VAR_1"

      - name: Fetch Hostname and Username
        env: 
          SELECTED_ENV: ${{ github.event.inputs.environment }}
          HOST_SFL: ${{ secrets.EC2_HOST_SFL }}
          USERNAME_SFL: ${{ secrets.EC2_USERNAME_SFL }}
          HOST_LMS: ${{ secrets.EC2_HOST_LMS }}
          USERNAME_LMS: ${{ secrets.EC2_USERNAME_LMS }}
        run: |
          if [ "$SELECTED_ENV" = "sfl" ]; then
            echo "Host: $HOST_SFL"
            echo "Username: $USERNAME_SFL"
          elif [ "$SELECTED_ENV" = "lms" ]; then
            echo "Host: $HOST_LMS"
            echo "Username: $USERNAME_LMS"
          else
            echo "Invalid environment selected."
          fi
