name: Transfer Files to EC2

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Select the environment"
        required: true
        default: "sfl"
        type: choice
        options:
          - sfl
          - lms

jobs:
  transfer:
    runs-on: ubuntu-latest

    steps:
      - name: Set environment-specific secrets
        id: set-secrets
        run: echo "EC2_HOST=${{ secrets['EC2_HOST_' + github.event.inputs.environment | upper }}}" >> $GITHUB_ENV &&
             echo "EC2_USERNAME=${{ secrets['EC2_USERNAME_' + github.event.inputs.environment | upper }}}" >> $GITHUB_ENV &&
             echo "SSH_PRIVATE_KEY=${{ secrets['SSH_PRIVATE_KEY_' + github.event.inputs.environment | upper }}}" >> $GITHUB_ENV

      - name: Transfer files to EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ env.EC2_HOST }}
          username: ${{ env.EC2_USERNAME }}
          key: ${{ env.SSH_PRIVATE_KEY }}
          source: 'super_admin_data.json'
          target: '/var/www/html/'
