name: Test Environment Secrets

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Select the environment"
        required: true
        default: "staging"
        type: choice
        options:
          - sfl
          - lms

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
   
    - name: Transfer files to EC2
      uses: appleboy/scp-action@v0.1.7
      with:
        host: ${{ secrets.EC2_HOST }}
	username: ${{ secrets.EC2_USERNAME }}
	key: ${{ secrets.SSH_PRIVATE_KEY }}
        source: 'super_admin_data.json'
        target: '/var/www/html/minerva/'
        strip_components: 2
