name: Test Environment Secrets

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Select the environment"
        required: true
        default: "staging"
        type: choice
        options:
          - sfl
          - lms

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
   
    - name: Run tests
      env:
        HOST: ${{ secrets.EC2_HOST }}
        USERNAME: ${{ secrets.EC2_USERNAME }}
        KEY: ${{ secrets.SSH_PRIVATE_KEY }}
    
    

    - name: Transfer files to EC2
      uses: appleboy/scp-action@v0.1.7
      with:
       host: ${{ env.HOST }}
        username: ${{ env.USERNAME }}
        key: ${{ env.KEY }}
        source: 'super_admin_data.json'
        target: '/var/www/html/minerva/'
        strip_components: 2
